module.exports = [
  {
    "city": "Sydney", 
    "lat": "-33.8650", 
    "lng": "151.2094", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "admin", 
    "population": "5312163", 
    "population_proper": "4840600"
  }, 
  {
    "city": "Melbourne", 
    "lat": "-37.8136", 
    "lng": "144.9631", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "admin", 
    "population": "5078193", 
    "population_proper": "4529500"
  }, 
  {
    "city": "Brisbane", 
    "lat": "-27.4678", 
    "lng": "153.0281", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "admin", 
    "population": "2514184", 
    "population_proper": "2360241"
  }, 
  {
    "city": "Perth", 
    "lat": "-31.9522", 
    "lng": "115.8589", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "admin", 
    "population": "2059484", 
    "population_proper": "2039200"
  }, 
  {
    "city": "Adelaide", 
    "lat": "-34.9289", 
    "lng": "138.6011", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "admin", 
    "population": "1345777", 
    "population_proper": "1295714"
  }, 
  {
    "city": "Gold Coast", 
    "lat": "-28.0167", 
    "lng": "153.4000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "679127", 
    "population_proper": "638090"
  }, 
  {
    "city": "Cranbourne", 
    "lat": "-38.0996", 
    "lng": "145.2834", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "460491", 
    "population_proper": "39419"
  }, 
  {
    "city": "Canberra", 
    "lat": "-35.2931", 
    "lng": "149.1269", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Australian Capital Territory", 
    "capital": "primary", 
    "population": "426704", 
    "population_proper": "381488"
  }, 
  {
    "city": "Newcastle", 
    "lat": "-32.9167", 
    "lng": "151.7500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "322278", 
    "population_proper": "152984"
  }, 
  {
    "city": "Wollongong", 
    "lat": "-34.4331", 
    "lng": "150.8831", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "302739", 
    "population_proper": "289236"
  }, 
  {
    "city": "Geelong", 
    "lat": "-38.1500", 
    "lng": "144.3500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "263280", 
    "population_proper": "191440"
  }, 
  {
    "city": "Hobart", 
    "lat": "-42.8806", 
    "lng": "147.3250", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Tasmania", 
    "capital": "admin", 
    "population": "240342", 
    "population_proper": "222356"
  }, 
  {
    "city": "Townsville", 
    "lat": "-19.2564", 
    "lng": "146.8183", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "180820", 
    "population_proper": "178649"
  }, 
  {
    "city": "Ipswich", 
    "lat": "-27.6167", 
    "lng": "152.7667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "163000", 
    "population_proper": "163000"
  }, 
  {
    "city": "Cairns", 
    "lat": "-16.9303", 
    "lng": "145.7703", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "152729", 
    "population_proper": "146778"
  }, 
  {
    "city": "Toowoomba", 
    "lat": "-27.5667", 
    "lng": "151.9500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "136861", 
    "population_proper": "135631"
  }, 
  {
    "city": "Darwin", 
    "lat": "-12.4381", 
    "lng": "130.8411", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Northern Territory", 
    "capital": "admin", 
    "population": "136828", 
    "population_proper": "136828"
  }, 
  {
    "city": "Ballarat", 
    "lat": "-37.5500", 
    "lng": "143.8500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "105471", 
    "population_proper": "98543"
  }, 
  {
    "city": "Bendigo", 
    "lat": "-36.7500", 
    "lng": "144.2667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "99122", 
    "population_proper": "95587"
  }, 
  {
    "city": "Launceston", 
    "lat": "-41.4419", 
    "lng": "147.1450", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Tasmania", 
    "capital": "", 
    "population": "87328", 
    "population_proper": "87328"
  }, 
  {
    "city": "Mackay", 
    "lat": "-21.1411", 
    "lng": "149.1861", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "80148", 
    "population_proper": "3659"
  }, 
  {
    "city": "Rockhampton", 
    "lat": "-23.3750", 
    "lng": "150.5117", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "78592", 
    "population_proper": "78592"
  }, 
  {
    "city": "Maitland", 
    "lat": "-32.7167", 
    "lng": "151.5500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "78015", 
    "population_proper": "1885"
  }, 
  {
    "city": "Bunbury", 
    "lat": "-33.3333", 
    "lng": "115.6333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "74363", 
    "population_proper": "71090"
  }, 
  {
    "city": "Coffs Harbour", 
    "lat": "-30.3022", 
    "lng": "153.1189", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "71822", 
    "population_proper": "25752"
  }, 
  {
    "city": "Bundaberg", 
    "lat": "-24.8500", 
    "lng": "152.3500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "70921", 
    "population_proper": "70540"
  }, 
  {
    "city": "Wagga Wagga", 
    "lat": "-35.1189", 
    "lng": "147.3689", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "56442", 
    "population_proper": "54411"
  }, 
  {
    "city": "Hervey Bay", 
    "lat": "-25.2853", 
    "lng": "152.8728", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "54674", 
    "population_proper": "54674"
  }, 
  {
    "city": "Shepparton", 
    "lat": "-36.3833", 
    "lng": "145.4000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "51631", 
    "population_proper": "31197"
  }, 
  {
    "city": "Albury", 
    "lat": "-36.0806", 
    "lng": "146.9158", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "47974", 
    "population_proper": "4804"
  }, 
  {
    "city": "Port Macquarie", 
    "lat": "-31.4333", 
    "lng": "152.9000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "47973", 
    "population_proper": "44830"
  }, 
  {
    "city": "Pakenham", 
    "lat": "-38.0712", 
    "lng": "145.4878", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "46421", 
    "population_proper": "46421"
  }, 
  {
    "city": "Tamworth", 
    "lat": "-31.0833", 
    "lng": "150.9167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "42872", 
    "population_proper": "180"
  }, 
  {
    "city": "Caloundra", 
    "lat": "-26.7986", 
    "lng": "153.1289", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "41293", 
    "population_proper": "41293"
  }, 
  {
    "city": "Orange", 
    "lat": "-33.2833", 
    "lng": "149.1000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "40493", 
    "population_proper": "38097"
  }, 
  {
    "city": "Dubbo", 
    "lat": "-32.2569", 
    "lng": "148.6011", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "38392", 
    "population_proper": "38392"
  }, 
  {
    "city": "Geraldton", 
    "lat": "-28.7744", 
    "lng": "114.6089", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "37648", 
    "population_proper": "37648"
  }, 
  {
    "city": "Nowra", 
    "lat": "-34.8833", 
    "lng": "150.6000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "37420", 
    "population_proper": "9193"
  }, 
  {
    "city": "Bathurst", 
    "lat": "-33.4200", 
    "lng": "149.5778", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "36801", 
    "population_proper": "35020"
  }, 
  {
    "city": "Queanbeyan", 
    "lat": "-35.3533", 
    "lng": "149.2342", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "36348", 
    "population_proper": "6237"
  }, 
  {
    "city": "Frankston", 
    "lat": "-38.1580", 
    "lng": "145.1350", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "36097", 
    "population_proper": "36097"
  }, 
  {
    "city": "Sunbury", 
    "lat": "-37.5811", 
    "lng": "144.7139", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "36084", 
    "population_proper": "36084"
  }, 
  {
    "city": "Warrnambool", 
    "lat": "-38.3833", 
    "lng": "142.4833", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "35214", 
    "population_proper": "29661"
  }, 
  {
    "city": "Wodonga", 
    "lat": "-36.1214", 
    "lng": "146.8881", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "35130", 
    "population_proper": "18948"
  }, 
  {
    "city": "Albany", 
    "lat": "-35.0228", 
    "lng": "117.8814", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "34205", 
    "population_proper": "29373"
  }, 
  {
    "city": "Gladstone", 
    "lat": "-23.8489", 
    "lng": "151.2625", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "33418", 
    "population_proper": "33418"
  }, 
  {
    "city": "Mildura", 
    "lat": "-34.1889", 
    "lng": "142.1583", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "32738", 
    "population_proper": "32738"
  }, 
  {
    "city": "Southport", 
    "lat": "-27.9667", 
    "lng": "153.4000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "31908", 
    "population_proper": "31908"
  }, 
  {
    "city": "Alice Springs", 
    "lat": "-23.7000", 
    "lng": "133.8667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Northern Territory", 
    "capital": "", 
    "population": "31120", 
    "population_proper": "31120"
  }, 
  {
    "city": "Dandenong", 
    "lat": "-37.9810", 
    "lng": "145.2150", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "29906", 
    "population_proper": "29906"
  }, 
  {
    "city": "Kalgoorlie", 
    "lat": "-30.7489", 
    "lng": "121.4658", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "29849", 
    "population_proper": "29849"
  }, 
  {
    "city": "Mount Gambier", 
    "lat": "-37.8294", 
    "lng": "140.7828", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "29639", 
    "population_proper": "25512"
  }, 
  {
    "city": "Lismore", 
    "lat": "-28.8167", 
    "lng": "153.2833", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "28720", 
    "population_proper": "3579"
  }, 
  {
    "city": "Maryborough", 
    "lat": "-25.5375", 
    "lng": "152.7019", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "27282", 
    "population_proper": "15406"
  }, 
  {
    "city": "Quakers Hill", 
    "lat": "-33.7344", 
    "lng": "150.8789", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "27080", 
    "population_proper": "27080"
  }, 
  {
    "city": "Gawler", 
    "lat": "-34.5981", 
    "lng": "138.7450", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "26472", 
    "population_proper": "942"
  }, 
  {
    "city": "Caboolture", 
    "lat": "-27.0667", 
    "lng": "152.9670", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "26433", 
    "population_proper": "26433"
  }, 
  {
    "city": "Ballina", 
    "lat": "-28.8333", 
    "lng": "153.5333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "26381", 
    "population_proper": "8655"
  }, 
  {
    "city": "Taree", 
    "lat": "-31.9000", 
    "lng": "152.4500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "26381", 
    "population_proper": "16197"
  }, 
  {
    "city": "Traralgon", 
    "lat": "-38.1958", 
    "lng": "146.5403", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "25485", 
    "population_proper": "24933"
  }, 
  {
    "city": "Busselton", 
    "lat": "-33.6478", 
    "lng": "115.3458", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "25329", 
    "population_proper": "25329"
  }, 
  {
    "city": "Armidale", 
    "lat": "-30.5000", 
    "lng": "151.6500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "24504", 
    "population_proper": "24504"
  }, 
  {
    "city": "Goulburn", 
    "lat": "-34.7547", 
    "lng": "149.6186", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "23835", 
    "population_proper": "22419"
  }, 
  {
    "city": "Devonport", 
    "lat": "-41.1806", 
    "lng": "146.3464", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Tasmania", 
    "capital": "", 
    "population": "23046", 
    "population_proper": "23046"
  }, 
  {
    "city": "Bacchus Marsh", 
    "lat": "-37.6750", 
    "lng": "144.4389", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "22223", 
    "population_proper": "6394"
  }, 
  {
    "city": "Whyalla", 
    "lat": "-33.0333", 
    "lng": "137.5667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "21742", 
    "population_proper": "21742"
  }, 
  {
    "city": "Cessnock", 
    "lat": "-32.8342", 
    "lng": "151.3555", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "21725", 
    "population_proper": "15177"
  }, 
  {
    "city": "Gympie", 
    "lat": "-26.1900", 
    "lng": "152.6655", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "21599", 
    "population_proper": "10803"
  }, 
  {
    "city": "Griffith", 
    "lat": "-34.2900", 
    "lng": "146.0400", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "20251", 
    "population_proper": "18196"
  }, 
  {
    "city": "Kwinana", 
    "lat": "-32.2394", 
    "lng": "115.7702", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "20086", 
    "population_proper": "17549"
  }, 
  {
    "city": "Burnie", 
    "lat": "-41.0636", 
    "lng": "145.8753", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Tasmania", 
    "capital": "", 
    "population": "19385", 
    "population_proper": "19385"
  }, 
  {
    "city": "Wangaratta", 
    "lat": "-36.3583", 
    "lng": "146.3125", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "19318", 
    "population_proper": "17377"
  }, 
  {
    "city": "Grafton", 
    "lat": "-29.6833", 
    "lng": "152.9333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "19078", 
    "population_proper": "10408"
  }, 
  {
    "city": "Yeppoon", 
    "lat": "-23.1333", 
    "lng": "150.7333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "19003", 
    "population_proper": "6334"
  }, 
  {
    "city": "Murray Bridge", 
    "lat": "-35.1170", 
    "lng": "139.2670", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "18779", 
    "population_proper": "14560"
  }, 
  {
    "city": "Mount Isa", 
    "lat": "-20.7333", 
    "lng": "139.5000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "18588", 
    "population_proper": "118"
  }, 
  {
    "city": "Narangba", 
    "lat": "-27.2015", 
    "lng": "152.9655", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "18573", 
    "population_proper": "18573"
  }, 
  {
    "city": "Mount Eliza", 
    "lat": "-38.1890", 
    "lng": "145.0920", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "17888", 
    "population_proper": "17888"
  }, 
  {
    "city": "Broken Hill", 
    "lat": "-31.9567", 
    "lng": "141.4678", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "17734", 
    "population_proper": "17734"
  }, 
  {
    "city": "Nerang", 
    "lat": "-27.9956", 
    "lng": "153.3220", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "16864", 
    "population_proper": "16864"
  }, 
  {
    "city": "Karratha", 
    "lat": "-20.7364", 
    "lng": "116.8464", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "16708", 
    "population_proper": "16708"
  }, 
  {
    "city": "Mount Barker", 
    "lat": "-35.0667", 
    "lng": "138.8500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "16629", 
    "population_proper": "13842"
  }, 
  {
    "city": "Horsham", 
    "lat": "-36.7167", 
    "lng": "142.2000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "16514", 
    "population_proper": "14543"
  }, 
  {
    "city": "Lara", 
    "lat": "-38.0167", 
    "lng": "144.4167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "16355", 
    "population_proper": "16355"
  }, 
  {
    "city": "Singleton", 
    "lat": "-32.5667", 
    "lng": "151.1697", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "16346", 
    "population_proper": "5000"
  }, 
  {
    "city": "Port Lincoln", 
    "lat": "-34.7322", 
    "lng": "135.8586", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "16326", 
    "population_proper": "14120"
  }, 
  {
    "city": "Banora Point", 
    "lat": "-28.2225", 
    "lng": "153.5386", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "16167", 
    "population_proper": "16167"
  }, 
  {
    "city": "Warwick", 
    "lat": "-28.2152", 
    "lng": "152.0352", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "15380", 
    "population_proper": "12222"
  }, 
  {
    "city": "Rochedale", 
    "lat": "-27.5952", 
    "lng": "153.1233", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "15317", 
    "population_proper": "15317"
  }, 
  {
    "city": "Kempsey", 
    "lat": "-31.0833", 
    "lng": "152.8333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "15309", 
    "population_proper": "474"
  }, 
  {
    "city": "Ulladulla", 
    "lat": "-35.3486", 
    "lng": "150.4678", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "15278", 
    "population_proper": "15278"
  }, 
  {
    "city": "Sale", 
    "lat": "-38.1000", 
    "lng": "147.0667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "15135", 
    "population_proper": "13673"
  }, 
  {
    "city": "Echuca", 
    "lat": "-36.1333", 
    "lng": "144.7500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "14934", 
    "population_proper": "14043"
  }, 
  {
    "city": "Australind", 
    "lat": "-33.2800", 
    "lng": "115.7260", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "14539", 
    "population_proper": "14539"
  }, 
  {
    "city": "Broome", 
    "lat": "-17.9619", 
    "lng": "122.2361", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "14445", 
    "population_proper": "4042"
  }, 
  {
    "city": "Port Hedland", 
    "lat": "-20.3100", 
    "lng": "118.6011", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "14320", 
    "population_proper": "4180"
  }, 
  {
    "city": "Warragul", 
    "lat": "-38.1500", 
    "lng": "145.9333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "14276", 
    "population_proper": "14276"
  }, 
  {
    "city": "Port Pirie", 
    "lat": "-33.1858", 
    "lng": "138.0169", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "14188", 
    "population_proper": "195"
  }, 
  {
    "city": "Barwon Heads", 
    "lat": "-38.2500", 
    "lng": "144.5167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "14165", 
    "population_proper": "14165"
  }, 
  {
    "city": "Emerald", 
    "lat": "-23.5167", 
    "lng": "148.1500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "14119", 
    "population_proper": "14119"
  }, 
  {
    "city": "Ulverstone", 
    "lat": "-41.1667", 
    "lng": "146.1667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Tasmania", 
    "capital": "", 
    "population": "14109", 
    "population_proper": "14109"
  }, 
  {
    "city": "Morwell", 
    "lat": "-38.2333", 
    "lng": "146.4000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "14026", 
    "population_proper": "13771"
  }, 
  {
    "city": "Gisborne", 
    "lat": "-37.4900", 
    "lng": "144.5889", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "13963", 
    "population_proper": "8999"
  }, 
  {
    "city": "Port Augusta", 
    "lat": "-32.4925", 
    "lng": "137.7658", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "South Australia", 
    "capital": "", 
    "population": "13799", 
    "population_proper": "6562"
  }, 
  {
    "city": "Forster", 
    "lat": "-32.1806", 
    "lng": "152.5117", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "13740", 
    "population_proper": "13740"
  }, 
  {
    "city": "Penrith", 
    "lat": "-33.7511", 
    "lng": "150.6942", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "13295", 
    "population_proper": "13295"
  }, 
  {
    "city": "Torquay", 
    "lat": "-38.3333", 
    "lng": "144.3167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "13258", 
    "population_proper": "13258"
  }, 
  {
    "city": "Jimboomba", 
    "lat": "-27.8333", 
    "lng": "153.0333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "13201", 
    "population_proper": "13201"
  }, 
  {
    "city": "Lithgow", 
    "lat": "-33.4833", 
    "lng": "150.1500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "12973", 
    "population_proper": "5201"
  }, 
  {
    "city": "Bowral", 
    "lat": "-34.4792", 
    "lng": "150.4181", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "12949", 
    "population_proper": "10335"
  }, 
  {
    "city": "Goonellabah", 
    "lat": "-28.8150", 
    "lng": "153.3178", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "12900", 
    "population_proper": "12900"
  }, 
  {
    "city": "Raymond Terrace", 
    "lat": "-32.7615", 
    "lng": "151.7441", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "12820", 
    "population_proper": "12820"
  }, 
  {
    "city": "Leopold", 
    "lat": "-38.1892", 
    "lng": "144.4644", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "12814", 
    "population_proper": "12814"
  }, 
  {
    "city": "Dalby", 
    "lat": "-27.1833", 
    "lng": "151.2667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "12719", 
    "population_proper": "12719"
  }, 
  {
    "city": "Campbelltown", 
    "lat": "-34.0733", 
    "lng": "150.8261", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "12566", 
    "population_proper": "12566"
  }, 
  {
    "city": "Colac", 
    "lat": "-38.3403", 
    "lng": "143.5847", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "12547", 
    "population_proper": "9048"
  }, 
  {
    "city": "Muswellbrook", 
    "lat": "-32.2654", 
    "lng": "150.8885", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "12364", 
    "population_proper": "12075"
  }, 
  {
    "city": "Esperance", 
    "lat": "-33.8611", 
    "lng": "121.8919", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "12145", 
    "population_proper": "2144"
  }, 
  {
    "city": "Drouin", 
    "lat": "-38.1333", 
    "lng": "145.8500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "11887", 
    "population_proper": "11887"
  }, 
  {
    "city": "Rutherford", 
    "lat": "-32.7150", 
    "lng": "151.5317", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "11884", 
    "population_proper": "11884"
  }, 
  {
    "city": "Nelson Bay", 
    "lat": "-32.7150", 
    "lng": "152.1511", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "11820", 
    "population_proper": "11820"
  }, 
  {
    "city": "Inverell", 
    "lat": "-29.7667", 
    "lng": "151.1167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "11660", 
    "population_proper": "11660"
  }, 
  {
    "city": "Parkes", 
    "lat": "-33.0950", 
    "lng": "148.2628", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "11408", 
    "population_proper": "11408"
  }, 
  {
    "city": "Somerville", 
    "lat": "-38.2260", 
    "lng": "145.1770", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "11336", 
    "population_proper": "11336"
  }, 
  {
    "city": "Gracemere", 
    "lat": "-23.4333", 
    "lng": "150.4500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "11315", 
    "population_proper": "11315"
  }, 
  {
    "city": "Batemans Bay", 
    "lat": "-35.7081", 
    "lng": "150.1744", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "11294", 
    "population_proper": "1530"
  }, 
  {
    "city": "Nambour", 
    "lat": "-26.6269", 
    "lng": "152.9592", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "11187", 
    "population_proper": "11187"
  }, 
  {
    "city": "Swan Hill", 
    "lat": "-35.3333", 
    "lng": "143.5500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "11103", 
    "population_proper": "9864"
  }, 
  {
    "city": "Mareeba", 
    "lat": "-16.9833", 
    "lng": "145.4167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "11079", 
    "population_proper": "11079"
  }, 
  {
    "city": "Corinda", 
    "lat": "-27.4833", 
    "lng": "153.1000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "11019", 
    "population_proper": "11019"
  }, 
  {
    "city": "Samford", 
    "lat": "-27.3667", 
    "lng": "152.8833", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "10931", 
    "population_proper": "796"
  }, 
  {
    "city": "Mudgee", 
    "lat": "-32.6125", 
    "lng": "149.5872", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "10923", 
    "population_proper": "10923"
  }, 
  {
    "city": "Casino", 
    "lat": "-28.8483", 
    "lng": "153.0511", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "10914", 
    "population_proper": "10914"
  }, 
  {
    "city": "Portland", 
    "lat": "-38.3333", 
    "lng": "141.6000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "10900", 
    "population_proper": "9712"
  }, 
  {
    "city": "Kingston", 
    "lat": "-42.9769", 
    "lng": "147.3083", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Tasmania", 
    "capital": "", 
    "population": "10409", 
    "population_proper": "10409"
  }, 
  {
    "city": "Kingaroy", 
    "lat": "-26.5333", 
    "lng": "151.8333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "10398", 
    "population_proper": "10020"
  }, 
  {
    "city": "Kangaroo Flat", 
    "lat": "-36.8000", 
    "lng": "144.2500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "10394", 
    "population_proper": "10394"
  }, 
  {
    "city": "Bowen", 
    "lat": "-20.0167", 
    "lng": "148.2333", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "10377", 
    "population_proper": "10377"
  }, 
  {
    "city": "Young", 
    "lat": "-34.3000", 
    "lng": "148.3000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "10295", 
    "population_proper": "10295"
  }, 
  {
    "city": "Cowra", 
    "lat": "-33.8183", 
    "lng": "148.6578", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "10063", 
    "population_proper": "10063"
  }, 
  {
    "city": "Hamilton", 
    "lat": "-37.7333", 
    "lng": "142.0167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "9974", 
    "population_proper": "9974"
  }, 
  {
    "city": "Gunnedah", 
    "lat": "-30.9667", 
    "lng": "150.2500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "9726", 
    "population_proper": "9726"
  }, 
  {
    "city": "Mount Evelyn", 
    "lat": "-37.7833", 
    "lng": "145.3833", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "9702", 
    "population_proper": "9702"
  }, 
  {
    "city": "Andergrove", 
    "lat": "-21.0931", 
    "lng": "149.1860", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "9419", 
    "population_proper": "9419"
  }, 
  {
    "city": "Moree", 
    "lat": "-29.4650", 
    "lng": "149.8344", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "9311", 
    "population_proper": "9311"
  }, 
  {
    "city": "Benalla", 
    "lat": "-36.5519", 
    "lng": "145.9817", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "9298", 
    "population_proper": "9298"
  }, 
  {
    "city": "Currumbin", 
    "lat": "-28.1580", 
    "lng": "153.4690", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "9121", 
    "population_proper": "9121"
  }, 
  {
    "city": "Wollert", 
    "lat": "-37.5970", 
    "lng": "145.0330", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "9060", 
    "population_proper": "9060"
  }, 
  {
    "city": "Mittagong", 
    "lat": "-34.4500", 
    "lng": "150.4500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8999", 
    "population_proper": "5767"
  }, 
  {
    "city": "Kelso", 
    "lat": "-33.4186", 
    "lng": "149.6056", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8968", 
    "population_proper": "8968"
  }, 
  {
    "city": "Yanchep", 
    "lat": "-31.5500", 
    "lng": "115.6340", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "8868", 
    "population_proper": "8868"
  }, 
  {
    "city": "Bentley", 
    "lat": "-32.0010", 
    "lng": "115.9240", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "8782", 
    "population_proper": "8782"
  }, 
  {
    "city": "Moe", 
    "lat": "-38.1722", 
    "lng": "146.2678", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "8778", 
    "population_proper": "8778"
  }, 
  {
    "city": "Ayr", 
    "lat": "-19.5744", 
    "lng": "147.4066", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "8738", 
    "population_proper": "8738"
  }, 
  {
    "city": "Moranbah", 
    "lat": "-22.0016", 
    "lng": "148.0533", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "8735", 
    "population_proper": "8735"
  }, 
  {
    "city": "Leeton", 
    "lat": "-34.5483", 
    "lng": "146.4011", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8623", 
    "population_proper": "8623"
  }, 
  {
    "city": "Moss Vale", 
    "lat": "-34.5483", 
    "lng": "150.3678", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8579", 
    "population_proper": "8579"
  }, 
  {
    "city": "Wallan", 
    "lat": "-37.4167", 
    "lng": "144.9833", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "8520", 
    "population_proper": "8504"
  }, 
  {
    "city": "Springwood", 
    "lat": "-33.6967", 
    "lng": "150.5683", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8475", 
    "population_proper": "8475"
  }, 
  {
    "city": "Lesmurdie", 
    "lat": "-31.9940", 
    "lng": "116.0500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "8437", 
    "population_proper": "8437"
  }, 
  {
    "city": "Forbes", 
    "lat": "-33.3833", 
    "lng": "148.0167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8432", 
    "population_proper": "8432"
  }, 
  {
    "city": "Emu Plains", 
    "lat": "-33.7483", 
    "lng": "150.6678", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8421", 
    "population_proper": "8421"
  }, 
  {
    "city": "Rye", 
    "lat": "-38.3770", 
    "lng": "144.8380", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "8416", 
    "population_proper": "8416"
  }, 
  {
    "city": "Darley", 
    "lat": "-37.6547", 
    "lng": "144.4370", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "8372", 
    "population_proper": "8372"
  }, 
  {
    "city": "Ararat", 
    "lat": "-37.2833", 
    "lng": "142.9167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "8300", 
    "population_proper": "8297"
  }, 
  {
    "city": "Tweed Heads", 
    "lat": "-28.1833", 
    "lng": "153.5500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "8176", 
    "population_proper": "8176"
  }, 
  {
    "city": "Highfields", 
    "lat": "-27.4581", 
    "lng": "151.9492", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "8131", 
    "population_proper": "8131"
  }, 
  {
    "city": "Charters Towers", 
    "lat": "-20.1000", 
    "lng": "146.2667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "8120", 
    "population_proper": "8120"
  }, 
  {
    "city": "Melton", 
    "lat": "-37.6833", 
    "lng": "144.5833", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "8069", 
    "population_proper": "8069"
  }, 
  {
    "city": "Katoomba", 
    "lat": "-33.7150", 
    "lng": "150.3120", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7964", 
    "population_proper": "7964"
  }, 
  {
    "city": "Kilmore", 
    "lat": "-37.2833", 
    "lng": "144.9500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7958", 
    "population_proper": "7958"
  }, 
  {
    "city": "Mooroopna", 
    "lat": "-36.3833", 
    "lng": "145.3500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7942", 
    "population_proper": "7942"
  }, 
  {
    "city": "Yarrawonga", 
    "lat": "-36.0167", 
    "lng": "146.0000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7930", 
    "population_proper": "7930"
  }, 
  {
    "city": "Maryborough", 
    "lat": "-37.0500", 
    "lng": "143.7350", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7921", 
    "population_proper": "7921"
  }, 
  {
    "city": "Deniliquin", 
    "lat": "-35.5317", 
    "lng": "144.9344", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7862", 
    "population_proper": "7862"
  }, 
  {
    "city": "Mandurah", 
    "lat": "-32.5289", 
    "lng": "115.7231", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "7837", 
    "population_proper": "7837"
  }, 
  {
    "city": "Bli Bli", 
    "lat": "-26.6180", 
    "lng": "153.0370", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "7801", 
    "population_proper": "7801"
  }, 
  {
    "city": "Kiama", 
    "lat": "-34.6708", 
    "lng": "150.8542", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7700", 
    "population_proper": "6881"
  }, 
  {
    "city": "Narre Warren North", 
    "lat": "-37.9833", 
    "lng": "145.3167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7674", 
    "population_proper": "7674"
  }, 
  {
    "city": "Narrabri", 
    "lat": "-30.3317", 
    "lng": "149.7678", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7606", 
    "population_proper": "7606"
  }, 
  {
    "city": "Bairnsdale", 
    "lat": "-37.8333", 
    "lng": "147.6167", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7580", 
    "population_proper": "7580"
  }, 
  {
    "city": "Clifton Springs", 
    "lat": "-38.1500", 
    "lng": "144.5667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7519", 
    "population_proper": "7519"
  }, 
  {
    "city": "North Tamborine", 
    "lat": "-27.9694", 
    "lng": "153.1992", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "7506", 
    "population_proper": "7506"
  }, 
  {
    "city": "Bargara", 
    "lat": "-24.8205", 
    "lng": "152.4625", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "7485", 
    "population_proper": "7485"
  }, 
  {
    "city": "Kingscliff", 
    "lat": "-28.2564", 
    "lng": "153.5781", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7464", 
    "population_proper": "7464"
  }, 
  {
    "city": "Healesville", 
    "lat": "-37.6561", 
    "lng": "145.5139", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7461", 
    "population_proper": "7461"
  }, 
  {
    "city": "Fremantle", 
    "lat": "-32.0569", 
    "lng": "115.7439", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "7459", 
    "population_proper": "7459"
  }, 
  {
    "city": "Blaxland", 
    "lat": "-33.7453", 
    "lng": "150.6175", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7451", 
    "population_proper": "7451"
  }, 
  {
    "city": "Atherton", 
    "lat": "-17.2658", 
    "lng": "145.4780", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "7331", 
    "population_proper": "7331"
  }, 
  {
    "city": "Kyabram", 
    "lat": "-36.3167", 
    "lng": "145.0500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "7321", 
    "population_proper": "7321"
  }, 
  {
    "city": "Innisfail", 
    "lat": "-17.5236", 
    "lng": "146.0292", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "7236", 
    "population_proper": "1145"
  }, 
  {
    "city": "Sanctuary Point", 
    "lat": "-35.1036", 
    "lng": "150.6267", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7225", 
    "population_proper": "7225"
  }, 
  {
    "city": "Collie", 
    "lat": "-33.3630", 
    "lng": "116.1560", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Western Australia", 
    "capital": "", 
    "population": "7192", 
    "population_proper": "7192"
  }, 
  {
    "city": "Gatton", 
    "lat": "-27.5611", 
    "lng": "152.2755", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "7101", 
    "population_proper": "7101"
  }, 
  {
    "city": "Merrimac", 
    "lat": "-28.0500", 
    "lng": "153.3667", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7071", 
    "population_proper": "7071"
  }, 
  {
    "city": "Murwillumbah", 
    "lat": "-28.3333", 
    "lng": "153.3833", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "7032", 
    "population_proper": "7032"
  }, 
  {
    "city": "Urraween", 
    "lat": "-25.2955", 
    "lng": "152.8219", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "6969", 
    "population_proper": "6969"
  }, 
  {
    "city": "Kyneton", 
    "lat": "-37.2333", 
    "lng": "144.4500", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "6951", 
    "population_proper": "6951"
  }, 
  {
    "city": "Bongaree", 
    "lat": "-27.0814", 
    "lng": "153.1633", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "6947", 
    "population_proper": "6947"
  }, 
  {
    "city": "Roma", 
    "lat": "-26.5733", 
    "lng": "148.7869", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "6848", 
    "population_proper": "6848"
  }, 
  {
    "city": "Mount Cotton", 
    "lat": "-27.6188", 
    "lng": "153.2210", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "6835", 
    "population_proper": "6835"
  }, 
  {
    "city": "Cootamundra", 
    "lat": "-34.6483", 
    "lng": "148.0344", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "6782", 
    "population_proper": "6782"
  }, 
  {
    "city": "Beerwah", 
    "lat": "-26.8556", 
    "lng": "152.9600", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "6769", 
    "population_proper": "6769"
  }, 
  {
    "city": "Castlemaine", 
    "lat": "-37.0636", 
    "lng": "144.2172", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "6757", 
    "population_proper": "6757"
  }, 
  {
    "city": "Pottsville", 
    "lat": "-28.3869", 
    "lng": "153.5608", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "6704", 
    "population_proper": "6704"
  }, 
  {
    "city": "Cooma", 
    "lat": "-36.2350", 
    "lng": "149.1258", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "6681", 
    "population_proper": "6681"
  }, 
  {
    "city": "Gordonvale", 
    "lat": "-17.0936", 
    "lng": "145.7866", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "6671", 
    "population_proper": "6671"
  }, 
  {
    "city": "Lysterfield", 
    "lat": "-37.9333", 
    "lng": "145.3000", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Victoria", 
    "capital": "", 
    "population": "6663", 
    "population_proper": "6663"
  }, 
  {
    "city": "Bomaderry", 
    "lat": "-34.8480", 
    "lng": "150.6050", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "New South Wales", 
    "capital": "", 
    "population": "6661", 
    "population_proper": "6661"
  }, 
  {
    "city": "Chinchilla", 
    "lat": "-26.7397", 
    "lng": "150.6250", 
    "country": "Australia", 
    "iso2": "AU", 
    "admin_name": "Queensland", 
    "capital": "", 
    "population": "6612", 
    "population_proper": "6612"
  }
]