module.exports.name = [
    "Brickstone",
    "Hop of the Hour ",
    "Paragon",
    "Strange ",
    "The Flying Compass",
    "Thirsty",
    "Dragonmead ",
    "The Last Glass",
    "Stone",
    "The Alabaster",
    "Black Widow",
    "Gorilla",
    "Hourglass",
    "Crossroad",
    "The Bison",
    "The Angel Wing",
    "Stranger Tides",
    "Flying Pig",
    "Black Diamond",
    "Nirvana",
    "The Omen",
    "Great Eastern",
    "Blizzard",
    "Mason",
    "High Rise",
    "Broken Farmer",
    "Tilted Tower",
    "Hellhound",
    "Eclipse",
    "Last Glass",
    "Bottom's Up",
    "Sunshine",
    "Pacific",
    "Classic",
    "Bootleg",
    "Twin Barrel",
    "Gold Rush",
    "Timeless",
    "Paradise",
    "The Victory",
    "Lone Tree",
    "Port Office",
    "The Post",
    "The Exchange",
    "Ironworks"
]

module.exports.suffix = [
    "Brewing",
    "Brewery",
    "Brewers",
    "Craft Ales",
    "Brewing Co.",
    "Brewing Company",
    "Fermentary",
    "Aleworks",
    "Ale House",
    "Pub",
    "Inn",
    "Bar",
    "Brewhouse",
    "Hotel",
    ""
]

module.exports.description = [
    "We are passionate about beer and we love what we do. Our beers are brewed using traditional methods and ingredients.",
    "Our beers are made using traditional methods and ingredients. They are brewed fresh every day and served as soon as possible after they have been bottled.",
    "We are passionate about beer and we want to share our passion with everyone. ",
    "Offers a wide variety of brews for you to enjoy. Their flagship is the Pint of Courage, a golden ale that has an alcohol content of 5.3%.",
    "Passionate about beer and we brew it using traditional methods - no additives or preservatives.",
    "Our beers have won awards at international beer competitions and our range includes ales, lagers, bitters and stouts.",
    "The company currently brews about 20,000 barrels of beer per year.",
    "Founded in 1896 by a German immigrant named Gottlieb Brekle. The brewery was originally known as Anchor Steam Beer and Malting Company.",
    "We use the highest quality ingredients to create unique and flavorful beers that reflect the diversity and creativity of our city. Our goal is to make great beer for everyone to enjoy.",
    "We specialize in small batch, artisanal beers that are handcrafted with the utmost care and attention to detail.",
    "Our goal is to produce the highest quality product possible, while also providing our customers with an enjoyable and memorable experience.",
    "The company was founded in 2014 by three friends who met while attending college together.",
    "The company's mission is to brew small batch, artisanal beers that are complex and flavorful, yet approachable and easy to drink.",
    "The brewery has won several awards for its beers, including a gold medal at the Great American Beer Festival and a silver medal at the World Beer Cup.",
    "Brewery that produces a variety of beers, including ales, lagers, and stouts.",
    "Wide selection of beers, including some that are seasonal.",
    "We specialize in unique and flavorful beers that are perfect for any occasion.",
    "Our taproom is open Wednesday-Sunday, and we offer tours of the brewery every Saturday.",
    "Small, independently owned and operated brewery.",
    "We specialize in small batch, artisanal beers that are designed to be unique and flavorful.",
    "Our goal is to create beers that we enjoy drinking and that we hope you will enjoy as well.",
    "The brewery was founded in 2012 by husband and wife team, Nate and Sarah Seale.",
    "The original brewery building is still standing and is now home to a microbrewery and pub."
]
